### ISSUE TITLE
Question about performance 

### ISSUE THREAD

**Issue by Akariya777** [DelphinusLab/halo2ecc-s#2]
I test the bls12-381 pairing on AWS EC2 instances (32-core, 256GB RAM) with GPU(v100, 16G), but it shows poor performance.
The `create proof` stage needs 1085s and it still cost 574s on v100, which is slower than the claimed [benchmark](https://ethresear.ch/t/zkpos-with-halo2-pairing-for-verifying-aggregate-bls-signatures/14671).
Do I need to turn on other settings?

commit id:1e0be3a654accb254f6b5cea0eec93ea657c789f

**Comment by lanbones** [comment]
Did you enable the feature `cuda`?

**Comment by Akariya777** [comment]
Yes, `create proof` costs 574 with feature `cuda`.

**Comment by lanbones** [comment]
I just test it on (i9-13900K 128G 4090)
command
```
cargo test bench_bls12_381_pairing_chip_over_bn256_fr --release --features cuda -- --nocapture
```
here is the log
```
Start:   create proof
··Start:   instance
··End:     instance ................................................................13.977µs
··Start:   advice
····Start:   assign
····End:     assign ................................................................597.655ms
····Start:   assign
····End:     assign ................................................................302.577ms
··End:     advice ..................................................................3.883s
··Start:   lookups
··End:     lookups .................................................................5.435s
··Start:   permutations comitted
··End:     permutations comitted ...................................................1.304s
··Start:   lookups commited
··End:     lookups commited ........................................................850.864ms
··Start:   vanishing commit
··End:     vanishing commit ........................................................304.143ms
··Start:   h_poly
····Start:   expressions
····End:     expressions ...........................................................1.127s
····Start:   permutations
····End:     permutations ..........................................................883.330ms
····Start:   eval_h_lookups
····End:     eval_h_lookups ........................................................983.693ms
··End:     h_poly ..................................................................3.182s
··Start:   vanishing construct
do once!
··End:     vanishing construct .....................................................1.187s
··Start:   eval poly
··End:     eval poly ...............................................................161.439ms
··Start:   eval poly vanishing
··End:     eval poly vanishing .....................................................68.445ms
··Start:   eval poly permutation
··End:     eval poly permutation ...................................................99.004ms
··Start:   eval poly lookups
··End:     eval poly lookups .......................................................57.139ms
··Start:   multi open
··End:     multi open ..............................................................2.755s
End:     create proof ..............................................................19.313s
```

Did you run the same command?

**Comment by Akariya777** [comment]
The cpu log with commond 
`cargo test bench_bls12_381_pairing_chip_over_bn256_fr -- --nocapture`

`running 1 test
offset 3115885 1250527
Start:   assign
End:     assign ....................................................................8.322s
Start:   assign
test tests::general_scalar_pairing_chip::bench_bls12_381_pairing_chip_over_bn256_fr has been running for over 60 seconds
End:     assign ....................................................................39.363s
offset 3115885 1250487
Start:   build params with K = 22
End:     build params with K = 22 ..................................................1156.833s
Start:   build vk
quotient_poly_degree 4
··Start:   assign
··End:     assign ..................................................................8.309s
··Start:   assign
··End:     assign ..................................................................6.352s
End:     build vk ..................................................................246.307s
quotient_poly_degree 4
Start:   assign
End:     assign ....................................................................8.307s
Start:   assign
End:     assign ....................................................................6.354s
Start:   build pk
··Start:   assign
··End:     assign ..................................................................8.163s
··Start:   assign
··End:     assign ..................................................................6.206s
End:     build pk ..................................................................486.792s
Start:   create proof
··Start:   instance
··End:     instance ................................................................187.928µs
··Start:   advice
····Start:   assign
····End:     assign ................................................................8.189s
····Start:   assign
····End:     assign ................................................................4.297s
··End:     advice ..................................................................145.187s
··Start:   lookups
··End:     lookups .................................................................205.264s
··Start:   permutations comitted
··End:     permutations comitted ...................................................85.540s
··Start:   lookups commited
··End:     lookups commited ........................................................64.708s
··Start:   vanishing commit
··End:     vanishing commit ........................................................28.701s
··Start:   h_poly
····Start:   expressions
····End:     expressions ...........................................................16.597s
····Start:   permutations
····End:     permutations ..........................................................15.235s
····Start:   eval_h_lookups
····End:     eval_h_lookups ........................................................89.203s
··End:     h_poly ..................................................................122.648s
··Start:   vanishing construct
do once!
··End:     vanishing construct .....................................................121.967s
··Start:   eval poly
··End:     eval poly ...............................................................2.571s
··Start:   eval poly vanishing
··End:     eval poly vanishing .....................................................662.568ms
··Start:   eval poly permutation
··End:     eval poly permutation ...................................................1.329s
··Start:   eval poly lookups
··End:     eval poly lookups .......................................................988.799ms
··Start:   multi open
··End:     multi open ..............................................................282.721s
End:     create proof ..............................................................1062.586s
Start:   verify proof
End:     verify proof ..............................................................43.144ms
test tests::general_scalar_pairing_chip::bench_bls12_381_pairing_chip_over_bn256_fr ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 12 filtered out; finished in 3614.53s`



And log on v100*4
build params with K = 22
`cargo test bench_bls12_381_pairing_chip_over_bn256_fr  --features="cuda" -- --nocapture`

`End:     build params with K = 22 ..................................................1447.571s
Start:   build vk
quotient_poly_degree 4
··Start:   assign
··End:     assign ..................................................................10.827s
··Start:   assign
··End:     assign ..................................................................8.127s
use cuda!!!!!!!!!!!!
End:     build vk ..................................................................85.129s
quotient_poly_degree 4
Start:   assign
End:     assign ....................................................................10.808s
Start:   assign
End:     assign ....................................................................8.104s
use cuda!!!!!!!!!!!!
Start:   build pk
··Start:   assign
··End:     assign ..................................................................10.796s
··Start:   assign
··End:     assign ..................................................................7.986s
End:     build pk ..................................................................54.810s
Start:   create proof
··Start:   instance
··End:     instance ................................................................241.814µs
··Start:   advice
····Start:   assign
····End:     assign ................................................................10.806s
····Start:   assign
····End:     assign ................................................................5.492s
use cuda!!!!!!!!!!!!
··End:     advice ..................................................................37.850s
··Start:   lookups
··End:     lookups .................................................................255.456s
··Start:   permutations comitted
··End:     permutations comitted ...................................................12.678s
··Start:   lookups commited
··End:     lookups commited ........................................................10.980s
··Start:   vanishing commit
use cuda!!!!!!!!!!!!
··End:     vanishing commit ........................................................4.342s
··Start:   h_poly
····Start:   expressions
····End:     expressions ...........................................................21.073s
····Start:   permutations
····End:     permutations ..........................................................19.366s
····Start:   eval_h_lookups
····End:     eval_h_lookups ........................................................3.006s
··End:     h_poly ..................................................................45.359s
··Start:   vanishing construct
do once!
use cuda!!!!!!!!!!!!
··End:     vanishing construct .....................................................10.740s
··Start:   eval poly
··End:     eval poly ...............................................................3.485s
··Start:   eval poly vanishing
··End:     eval poly vanishing .....................................................815.505ms
··Start:   eval poly permutation
··End:     eval poly permutation ...................................................1.718s
··Start:   eval poly lookups
··End:     eval poly lookups .......................................................1.317s
··Start:   multi open
use cuda!!!!!!!!!!!!
··End:     multi open ..............................................................28.405s
End:     create proof ..............................................................413.501s
Start:   verify proof
End:     verify proof ..............................................................60.061ms
test tests::general_scalar_pairing_chip::bench_bls12_381_pairing_chip_over_bn256_fr ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 15 filtered out; finished in 2112.31s`
You can even see the log `use cuda!!!!!!!!!!` :)

**Comment by lanbones** [comment]
I think the difference is on `--release`. You ran it with debug version.

**Comment by Akariya777** [comment]
Got it! Thanks for your help!
